-- CreateTable
CREATE TABLE "Part" (
    "id" SERIAL NOT NULL,
    "customer" TEXT NOT NULL,
    "assyPartNo" TEXT NOT NULL,
    "subAssyPartNo" TEXT NOT NULL,
    "qualityPlanAvailable" BOOLEAN NOT NULL,
    "idA" DOUBLE PRECISION NOT NULL,
    "plugGaugeAvailableA" BOOLEAN NOT NULL,
    "idB" DOUBLE PRECISION NOT NULL,
    "plugGaugeAvailableB" BOOLEAN NOT NULL,
    "wallThicknessA" DOUBLE PRECISION NOT NULL,
    "wallThicknessB" DOUBLE PRECISION NOT NULL,
    "flareLengthMin" DOUBLE PRECISION NOT NULL,
    "endCapLengthMin" DOUBLE PRECISION NOT NULL,
    "profileFixtureAvailable" BOOLEAN NOT NULL,
    "hardness" DOUBLE PRECISION NOT NULL,
    "hardnessPinGaugeAvailable" BOOLEAN NOT NULL,
    "notchingRequired" BOOLEAN NOT NULL,
    "notchingToolAvailable" BOOLEAN NOT NULL,
    "connectorRequired" BOOLEAN NOT NULL,
    "connectorFixtureAvailable" BOOLEAN NOT NULL,
    "oetikerClampRequired" BOOLEAN NOT NULL,
    "oetikerClampFixture" BOOLEAN NOT NULL,
    "mubeaClamp" BOOLEAN NOT NULL,
    "mubeaClampFixture" BOOLEAN NOT NULL,
    "springBandClamp" BOOLEAN NOT NULL,
    "heatSinkSleeve" BOOLEAN NOT NULL,
    "assyProfileFixtureAvailable" BOOLEAN NOT NULL,
    "leakageTestingRequired" BOOLEAN NOT NULL,
    "leakageTestingPerformed" BOOLEAN NOT NULL,
    "leakageFixtureAvailable" BOOLEAN NOT NULL,
    "numLeakageFixtures" INTEGER NOT NULL,
    "cleanlinessMiliporeTest" BOOLEAN NOT NULL,
    "burstReqAvailable" BOOLEAN NOT NULL,
    "pullOutLoad" DOUBLE PRECISION NOT NULL,
    "vacuumTestingRequired" BOOLEAN NOT NULL,
    "vacuumTestingPerformed" BOOLEAN NOT NULL,
    "padPrintingFixture" BOOLEAN NOT NULL,

    CONSTRAINT "Part_pkey" PRIMARY KEY ("id")
);
